### PR TITLE
omit Linux executables in a Windows build and vice versa

### PR DESCRIPTION
**Pull request by guoci**
decreases `Philosopher` binaries size by about 45%

### CODE REVIEW

**Comment by prvst** [comment]
Hi @guoci, can you describe to me what you did here? Slack works fine if you prefer.

**Comment by guoci** [comment]
In the `philosopher.exe` (Windows binary) you have Linux executables (`proteinprohet`, `peptideprophet`, etc) packed within it and vice versa. This causes the compiled Philosopher binaries to be way larger than it needs to be.
This commits uses [build constraints](https://pkg.go.dev/go/build#hdr-Build_Constraints) to omit cross-OS executables. So now `philosopher.exe` will only have Windows executables within it.

**Comment by prvst** [comment]
Did you test the program on both Windows and Linux, after removing the extra files?

**Comment by prvst** [comment]
OK, in that case, I'll hold the merging to the RC branch until we know it works. Thanks for the update.

**Pull request merged**
